# Generated by Django 4.1.7 on 2023-04-10 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
